[build]
rustflags = [
    "-W", "missing_docs",
]
incremental = true

[target.x86_64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[profile.release]
strip = true

[tools.clippy]
warn = [
    "missing_docs_in_private_items",
]
